# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4cd36c18f185844518392154b098c7764f93c8129c5e4e225a5fc796ec8a3d8ec2714aac4b40746284a12f9fbc8ae6bd223017ae991888f5e3eb9b911af4362

test:
  secret_key_base: a3993e018293d94f7a0dbca30a686a0e8592a7e02b95f45fde7015653b85a66d68513ed251c9a7f65d4dcbd6d5f5a3808c016a340c2660b3235f9ef0b429b766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
